name: Run Data Agents Workflow

on:
  schedule:
    # Run daily at 8 AM UTC
    - cron: '* * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-agents:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
           pip install supabase
           pip install openai
           pip install requests
           pip install datetime
      
      - name: Set up environment variables
        run: |
          # Create .env file from GitHub secrets
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Fetch news from Brave API
        run: python ECO_NEWS.py
        
      - name: Fetch Bitcoin prices
        run: python BITCOIN_PRICES.py
      
      - name: Compile data and generate email
        run: python EMAIL AGENT.py
